# Generated by Django 5.2.10 on 2026-02-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpricing',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='userpricing',
            name='gpu',
        ),
        migrations.AddField(
            model_name='userpricing',
            name='ai_cpu_recommendation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='ai_gpu_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='ai_gpu_recommendation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='ai_ram_recommendation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='ai_system_tier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
