# Generated by Django 5.2.10 on 2026-02-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0002_rename_duartion_component_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='VRAM',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
