# Generated by Django 5.2.10 on 2026-02-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0002_remove_userpricing_cpu_remove_userpricing_gpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='ai_gpu_vram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='ai_total_vram',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
