# Generated by Django 5.2.10 on 2026-02-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0003_alter_component_vram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpricing',
            name='licence',
        ),
    ]
