# Generated by Django 5.2.10 on 2026-02-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0003_userpricing_ai_gpu_vram_userpricing_ai_total_vram'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='ai_cpu_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
