# Generated by Django 5.2.10 on 2026-02-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0004_remove_userpricing_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenseCosting', to='pricingModel.component'),
        ),
    ]
