# Generated by Django 5.2.10 on 2026-01-14 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_ENABLED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AI_feature', models.CharField(max_length=50)),
                ('costing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cammera_Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cammera', models.IntegerField()),
                ('max_cammera', models.IntegerField()),
                ('Processor', models.CharField(max_length=50)),
                ('total_costing', models.IntegerField()),
            ],
            options={
                'ordering': ['min_cammera'],
            },
        ),
        migrations.CreateModel(
            name='UserPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cammera', models.IntegerField()),
                ('total_costing', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_features', models.ManyToManyField(blank=True, to='pricingModel.ai_enabled')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
