# Generated by Django 5.2.10 on 2026-01-23 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE_QUOTATION', 'Create Quotation'), ('DOWNLOAD_PDF', 'Download PDF'), ('SEND_EMAIL', 'Send Email'), ('DELETE_QUOTATION', 'Delete Quotation'), ('UPDATE_PRICING', 'Update Pricing')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_cammera', models.IntegerField(blank=True, null=True)),
                ('max_cammera', models.IntegerField(blank=True, null=True)),
                ('CPUcores', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_required', models.PositiveIntegerField(blank=True, help_text='GB', null=True)),
                ('AI_feature', models.CharField(blank=True, max_length=100, null=True)),
                ('min_cammeraA', models.IntegerField(blank=True, null=True)),
                ('max_cammeraA', models.IntegerField(blank=True, null=True)),
                ('VRAM', models.CharField(blank=True, max_length=50)),
                ('storage_per_cam', models.IntegerField(blank=True, null=True)),
                ('storage_perDay', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricingModel.category')),
            ],
            options={
                'ordering': ['min_cammera'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costing', models.IntegerField()),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='pricingModel.component')),
            ],
        ),
        migrations.CreateModel(
            name='UserPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cammera', models.IntegerField()),
                ('aiEnabledCam', models.IntegerField(blank=True, null=True)),
                ('vram_required', models.IntegerField()),
                ('cpuCores_required', models.IntegerField()),
                ('ram_required', models.IntegerField()),
                ('storage_used_user', models.IntegerField(default=19)),
                ('storage_days', models.IntegerField(default=1)),
                ('ai_cost', models.IntegerField(default=0)),
                ('storage_cost', models.IntegerField(default=0)),
                ('total_costing', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_features', models.ManyToManyField(blank=True, related_name='user_pricings', to='pricingModel.component')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
