# Generated by Django 5.2.10 on 2026-01-20 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('min_cammera', models.IntegerField(blank=True, null=True)),
                ('max_cammera', models.IntegerField(blank=True, null=True)),
                ('AI_feature', models.CharField(blank=True, max_length=100, null=True)),
                ('CPU', models.CharField(blank=True, max_length=50, null=True)),
                ('GPU', models.CharField(blank=True, max_length=50, null=True)),
                ('CPUcores', models.PositiveIntegerField(null=True)),
                ('GPUcores', models.PositiveIntegerField(null=True)),
                ('ram_required', models.PositiveIntegerField(blank=True, help_text='GB', null=True)),
                ('storage_per_cam', models.IntegerField(blank=True, null=True)),
                ('storage_perDay', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricingModel.category')),
            ],
            options={
                'ordering': ['min_cammera'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costing', models.IntegerField()),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricingModel.component')),
            ],
        ),
        migrations.CreateModel(
            name='UserPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cammera', models.IntegerField()),
                ('camera_cost', models.IntegerField(default=0)),
                ('ai_cost', models.IntegerField(default=0)),
                ('processor_cost', models.IntegerField(default=0)),
                ('storage_cost', models.IntegerField(default=0)),
                ('total_costing', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_features', models.ManyToManyField(blank=True, related_name='user_pricings', to='pricingModel.component')),
                ('processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_processing_unit', to='pricingModel.component')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_storage', to='pricingModel.component')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
