# Generated by Django 5.2.10 on 2026-01-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpricing',
            name='aiEnabledCam',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
