# Generated by Django 5.2.10 on 2026-01-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='costing',
        ),
    ]
