# Generated by Django 5.2.10 on 2026-01-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='component',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='pricingModel.component'),
            preserve_default=False,
        ),
    ]
