# Generated by Django 5.2.10 on 2026-01-23 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='AI_Component',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='core_hardware',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpu_usages', to='pricingModel.component'),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='cpu_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpu_usages', to='pricingModel.component'),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='gpu_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='aiEnabledCam',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='ai_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='cammera',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='cpuCores_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='ram_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='storage_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='storage_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='storage_used_user',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='total_costing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='vram_required',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
