# Generated by Django 5.2.10 on 2026-02-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='Duartion',
            new_name='Duration',
        ),
    ]
