# Generated by Django 5.2.10 on 2026-01-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0002_remove_price_costing'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='costing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
