# Generated by Django 5.2.10 on 2026-01-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0002_remove_userpricing_ai_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpricing',
            name='camera_cost',
        ),
        migrations.AddField(
            model_name='userpricing',
            name='ai_features',
            field=models.ManyToManyField(blank=True, related_name='user_pricings', to='pricingModel.component'),
        ),
    ]
