# Generated by Django 5.2.10 on 2026-01-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0002_component_ai_component_component_core_hardware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='AI_Component',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='core_hardware',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
