# Generated by Django 5.2.10 on 2026-01-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0002_remove_userpricing_total_costing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='total_costing',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
