# Generated by Django 5.2.10 on 2026-01-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0003_userpricing_total_costing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cammera_pricing',
            name='max_cammera',
            field=models.IntegerField(null=True),
        ),
    ]
