# Generated by Django 5.2.10 on 2026-01-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0003_price_costing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='costing',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
