# Generated by Django 5.2.10 on 2026-01-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0003_remove_userpricing_camera_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='camera_cost',
            field=models.IntegerField(default=0),
        ),
    ]
