# Generated by Django 5.2.10 on 2026-02-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0003_alter_component_ai_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='include_ai',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='include_cpu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='include_gpu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='include_storage',
            field=models.BooleanField(default=True),
        ),
    ]
