# Generated by Django 5.2.10 on 2026-01-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0004_alter_cammera_pricing_max_cammera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cammera_pricing',
            name='max_cammera',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
