# Generated by Django 5.2.10 on 2026-02-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0004_userpricing_include_ai_userpricing_include_cpu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpricing',
            name='include_ai',
        ),
    ]
