# Generated by Django 5.2.6 on 2026-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0005_alter_cammera_pricing_max_cammera'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='ai_cost',
            field=models.IntegerField(default=0),
        ),
    ]
