# Generated by Django 5.2.10 on 2026-02-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0005_remove_userpricing_include_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='Duartion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userpricing',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenseCosting', to='pricingModel.component'),
        ),
    ]
