# Generated by Django 5.2.6 on 2026-01-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0006_userpricing_ai_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='camera_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpricing',
            name='total_costing',
            field=models.IntegerField(default=0),
        ),
    ]
