# Generated by Django 5.2.10 on 2026-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0006_component_duartion_userpricing_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='Duration',
            field=models.IntegerField(default=1),
        ),
    ]
