# Generated by Django 5.2.10 on 2026-02-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0007_userpricing_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='licenceCostU',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
