# Generated by Django 5.2.6 on 2026-02-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0008_userpricing_licencecostu'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='include_ai',
            field=models.BooleanField(default=True),
        ),
    ]
