# Generated by Django 5.2.6 on 2026-01-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0008_pdfdownloadlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfDownloadLog',
        ),
    ]
