# Generated by Django 5.2.6 on 2026-01-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0009_delete_pdfdownloadlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cammera_pricing',
            name='Processor',
        ),
    ]
