# Generated by Django 5.2.6 on 2026-01-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0010_remove_cammera_pricing_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='storage_days',
            field=models.IntegerField(default=1),
        ),
    ]
