# Generated by Django 5.2.10 on 2026-01-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingModel', '0011_userpricing_storage_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpricing',
            name='storage_used_user',
            field=models.IntegerField(default=19),
        ),
    ]
